# Use latest node image
image: node:latest

# Cache npm dependencies
cache:
  key: static-marks
  paths:
    - .npm/

before_script:
  - npm install static-marks --cache .npm --prefer-offline

test:
  script:
    - mkdir -p public
    - ./node_modules/.bin/static-marks build src/data/bookmarks/*.yml > public/bookmarks/index.html
  artifacts:
    paths:
      - public/bookmarks
  only:
    - branches
  except:
    - main

pages:
  script:
    - mkdir -p public/bookmarks
    - ./node_modules/.bin/static-marks build src/data/bookmarks/*.yml > public/bookmarks/index.html
  artifacts:
    paths:
      - public
  only:
    - main